### ISSUE TITLE
Command-line arguments

### ISSUE THREAD

**Issue by dohliam** [kdelaney/germanipa#1]
Thanks for this great project! You might like to know that germanipa is being used as the basis for a [German IPA dictionary](https://github.com/open-dict-data/ipa-dict). To facilitate this process, I made a few tiny changes to the script to [allow it to take phrases as command-line arguments](https://github.com/dohliam/germanipa), which makes it a lot easier to redirect the output to other places / tools. If you think that might be useful I'd be happy to submit a PR with the changes. :smile:

**Comment by kdelaney** [comment]
Cool! I'd love it if you made the PR.
